services:
  db:
    image: postgis/postgis:18-3.6
    container_name: lead-time-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - lead-time-data:/var/lib/postgresql
      - ./db/migrations:/migrations:ro

volumes:
  lead-time-data:
